export const COUNTRY_CODES = [
	{ value: "+355", label: "🇦🇱 Albania" },
	{ value: "+213", label: "🇩🇿 Algeria" },
	{ value: "+54", label: "🇦🇷 Argentina" },
	{ value: "+61", label: "🇦🇺 Australia" },
	{ value: "+43", label: "🇦🇹 Austria" },
	{ value: "+32", label: "🇧🇪 Belgium" },
	{ value: "+55", label: "🇧🇷 Brazil" },
	{ value: "+359", label: "🇧🇬 Bulgaria" },
	{ value: "+1", label: "🇺🇸🇨🇦 US / Canada" },
	{ value: "+56", label: "🇨🇱 Chile" },
	{ value: "+86", label: "🇨🇳 China" },
	{ value: "+57", label: "🇨🇴 Colombia" },
	{ value: "+385", label: "🇭🇷 Croatia" },
	{ value: "+357", label: "🇨🇾 Cyprus" },
	{ value: "+420", label: "🇨🇿 Czechia" },
	{ value: "+45", label: "🇩🇰 Denmark" },
	{ value: "+20", label: "🇪🇬 Egypt" },
	{ value: "+358", label: "🇫🇮 Finland" },
	{ value: "+33", label: "🇫🇷 France" },
	{ value: "+49", label: "🇩🇪 Germany" },
	{ value: "+30", label: "🇬🇷 Greece" },
	{ value: "+36", label: "🇭🇺 Hungary" },
	{ value: "+91", label: "🇮🇳 India" },
	{ value: "+62", label: "🇮🇩 Indonesia" },
	{ value: "+353", label: "🇮🇪 Ireland" },
	{ value: "+972", label: "🇮🇱 Israel" },
	{ value: "+39", label: "🇮🇹 Italy" },
	{ value: "+81", label: "🇯🇵 Japan" },
	{ value: "+962", label: "🇯🇴 Jordan" },
	{ value: "+254", label: "🇰🇪 Kenya" },
	{ value: "+82", label: "🇰🇷 South Korea" },
	{ value: "+961", label: "🇱🇧 Lebanon" },
	{ value: "+352", label: "🇱🇺 Luxembourg" },
	{ value: "+60", label: "🇲🇾 Malaysia" },
	{ value: "+356", label: "🇲🇹 Malta" },
	{ value: "+212", label: "🇲🇦 Morocco" },
	{ value: "+52", label: "🇲🇽 Mexico" },
	{ value: "+31", label: "🇳🇱 Netherlands" },
	{ value: "+64", label: "🇳🇿 New Zealand" },
	{ value: "+234", label: "🇳🇬 Nigeria" },
	{ value: "+47", label: "🇳🇴 Norway" },
	{ value: "+92", label: "🇵🇰 Pakistan" },
	{ value: "+63", label: "🇵🇭 Philippines" },
	{ value: "+48", label: "🇵🇱 Poland" },
	{ value: "+351", label: "🇵🇹 Portugal" },
	{ value: "+40", label: "🇷🇴 Romania" },
	{ value: "+7", label: "🇷🇺 Russia" },
	{ value: "+966", label: "🇸🇦 Saudi Arabia" },
	{ value: "+381", label: "🇷🇸 Serbia" },
	{ value: "+65", label: "🇸🇬 Singapore" },
	{ value: "+421", label: "🇸🇰 Slovakia" },
	{ value: "+386", label: "🇸🇮 Slovenia" },
	{ value: "+27", label: "🇿🇦 South Africa" },
	{ value: "+34", label: "🇪🇸 Spain" },
	{ value: "+94", label: "🇱🇰 Sri Lanka" },
	{ value: "+46", label: "🇸🇪 Sweden" },
	{ value: "+41", label: "🇨🇭 Switzerland" },
	{ value: "+66", label: "🇹🇭 Thailand" },
	{ value: "+216", label: "🇹🇳 Tunisia" },
	{ value: "+90", label: "🇹🇷 Turkey" },
	{ value: "+380", label: "🇺🇦 Ukraine" },
	{ value: "+971", label: "🇦🇪 UAE" },
	{ value: "+44", label: "🇬🇧 United Kingdom" },
] as const;
